version: '3'


services:
        omp:
                build: .
                environment:
                        - REDIS_HOST=redis
                ports:
                        - "5000:5000"
        redis:
                image: redis
